# ----------------------------------------------------------------------------------------------------------------------
# Swagger
# ----------------------------------------------------------------------------------------------------------------------
springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger.html"
  show-actuator: true
