# ----------------------------------------------------------------------------------------------------------------------
# debug模式
# ----------------------------------------------------------------------------------------------------------------------
debug:
  false

# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: "playground"
  profiles:
    active:
      - "dev"
      - "swagger"
    include:
      - "ssl"
  config:
    import: [ ]
  autoconfigure:
    exclude:
      - "org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration"
  aop:
    auto: true
  main:
    web-application-type: servlet
    banner-mode: log
    allow-bean-definition-overriding: true
    allow-circular-references: false
    log-startup-info: true
    cloud-platform: none
    lazy-initialization: false
    register-shutdown-hook: true
    sources: [ ]
  banner:
    location: "classpath:/META-INF/banner.txt"
  jackson:
    locale: "zh_CN"
    time-zone: "Asia/Shanghai"
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    default-property-inclusion: always
    serialization:
      indent-output: true
      fail-on-self-references: true
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
      write-null-map-values: true
      write-empty-json-arrays: true
      write-single-elem-arrays-unwrapped: false
      write-enums-using-to-string: true
    deserialization:
      fail-on-unknown-properties: false
    mapper:
      default-view-inclusion: true
      accept-case-insensitive-enums: true
  lifecycle:
    timeout-per-shutdown-phase: "30s"
  jmx:
    enabled: false
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      enabled: true
      max-file-size: "1GB"
      max-request-size: "2GB"
  pid:
    file: "/var/run/${spring.application.name}/pid"
    fail-on-write-error: false
  #  datasource:
  #    type: com.zaxxer.hikari.HikariDataSource
  #    hikari:
  #      pool-name: "HikariCP"
  #      minimum-idle: 10
  #      maximum-pool-size: 30
  #      auto-commit: true
  #      idle-timeout: 30000
  #      max-lifetime: 900000
  #      connection-timeout: 10000
  #      connection-test-query: "SELECT 0"
  #      validation-timeout: 1000
  flyway:
    enabled: false
  security:
    filter:
      order: -200
  task:
    execution:
      thread-name-prefix: "common-task-"
      pool:
        core-size: 15
        max-size: 30
        keep-alive: 60s
        queue-capacity: 45
        allow-core-thread-timeout: true
  data:
    jdbc:
      repositories:
        enabled: false

# ----------------------------------------------------------------------------------------------------------------------
# 服务器相关配置
# ----------------------------------------------------------------------------------------------------------------------
server:
  port: 8443
  ssl:
    enabled: true
    protocol: "TLS"
    client-auth: want
    certificate: "classpath:/secret/server.pem"
    certificate-private-key: "classpath:/secret/server.pem"
    trust-certificate: "classpath:/secret/trust.pem"
  servlet:
    context-path: "/"
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    min-response-size: "1KB"
  shutdown: graceful
  tomcat:
    threads:
      max: 400

# ----------------------------------------------------------------------------------------------------------------------
# Actuator
# ----------------------------------------------------------------------------------------------------------------------
management:
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
    env:
      show-values: when_authorized
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    build:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
    jmx:
      domain: "com.github.yingzhuo.playground"
      exposure:
        include: "*"

info:
  authors:
    - name: "应卓"
      email: "yingzhor@gmail.com"
  description: "竞技场"

# ----------------------------------------------------------------------------------------------------------------------
# This Application
# ----------------------------------------------------------------------------------------------------------------------
playground:
  jwt:
    issuer: "playground.com"
    ttl: "3d"

# ----------------------------------------------------------------------------------------------------------------------
# MyBatis / MyBatis-Plus
# ----------------------------------------------------------------------------------------------------------------------
mybatis-plus:
  global-config:
    banner: false
    db-config:
      table-prefix: "t_"
  mapperLocations:
    - "classpath*:/mybatis-mapper/**/*Mapper.xml"
  type-aliases-package: com.github.yingzhuo.playground.entity,com.github.yingzhuo.playground.dto

# ----------------------------------------------------------------------------------------------------------------------
# SQL日志
# ----------------------------------------------------------------------------------------------------------------------
#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true
#      multiline: true
#      logging: slf4j

# ----------------------------------------------------------------------------------------------------------------------
# Swagger
# ----------------------------------------------------------------------------------------------------------------------
springdoc:
  swagger-ui:
    enabled: false
