# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  config:
    import: [ ]
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "root"
    password: "root"
    url: "jdbc:mysql://127.0.0.1:3306/SpringBootPlayground"
  data:
    redis:
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
        cluster:
          refresh:
            adaptive: true # 在集群模式下必须要自动刷新拓扑
            period: 2s
      database: 0
      host: "localhost"
      port: 6379
      password: "133810"
#      cluster:
#        nodes: ""

# ----------------------------------------------------------------------------------------------------------------------
# 分布式锁配置
# ----------------------------------------------------------------------------------------------------------------------
red-lock:
  enabled: true
  allow-downgrade-to-non-multi-lock: true
  nodes:
    - address: "redis://localhost:6379"
      username: ""
      password: "133810"
  aspect-advice:
    enabled: true
